title: Boyun Li
position: Postdoc Fellow
affiliation: University of Macau, China
email: liboyun.gm@gmail.com
scholar: https://scholar.google.com/citations?user=CnTYMosAAAAJ
keywords: Boyun Li
google_scholar: 
github_link: 
linkedin: 
avatar: ./assets/img/avatar.jpg
google_analytics: 
favicon: 
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: liboyun.github.io
